# Application port
server:
  port: 8082

# Default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    # PostgreSQL
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/dev}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  # Default Schema
  flyway:
    schemas: shopping
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    properties:
      hibernate:
        default_schema: shopping

